config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :students
  get 'books/index'
  get 'home/about'
  get  'students/index'
  root 'books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
	has_one:student
	
end

app/models/student.rb
class Student < ApplicationRecord
  # Callbacks

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    @students= Student.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_name, :author_name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Book name:</strong>
    <%= book.book_name %>
  </p>

  <p>
    <strong>Author name:</strong>
    <%= book.author_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :book_name, style: "display: block" %>
    <%= form.text_field :book_name,class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author_name, style: "display: block" %>
    <%= form.text_field :author_name,class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:'form-control' %>
  </div>

  <br/>
  <%= form.submit class:'btn btn-info' %>   
  </div>
 
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>


<div id="books">
  <div class="jumbotron" >
  <table class="table table-striped table-bordered table-hover">
      <thead class="table-light">
      <tr>
        <th>Book Name</th>
         
        <th>Author Name</th>
        
        <th>Description</th>
        <th></th>
        <th></th>

    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%=book.book_name%></td>
        <td><%=book.author_name%></td>
        <td ><%=book.description%></td>
        <td> <%= link_to "Show this book", book ,class:'btn btn-warning'%> </td>
        <td><%= link_to "Update", edit_book_path(book),class:'btn btn-info' %> </td>
        <td><%= button_to "Delete", book, method: :delete ,class:'btn btn-danger' %></td>
        <td><select name="cars" id="cars">
          <%@students.each do|student|%>
          <option value="<%=student.name%>"><%=student.name%></option>
          <%end%>
          </select> <%= link_to "Assign Book", book ,class:'btn btn-secondary' %> 
        </td>
      </tr>
      <%end %>
    </tbody>
</table>
</div>

<div class="container">
      <%= link_to "Add Books", new_book_path,class:'btn btn-success' %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div class="container">
  <%= link_to "Back to books", books_path,class:'btn btn-secondary' %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book),class:'btn btn-secondary' %> 
  <%= link_to "Back to books", books_path,class:'btn btn-secondary' %>
  <br>

  <br>
  <%= button_to "Destroy this book", @book, method: :delete,class:'btn btn-danger' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'College Library',root_path,class:"navbar-brand" %>
   <!-- <a class="navbar-brand" href="#">Library Management</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Students',students_path,class:"nav-link" %>
       <!--   <a class="nav-link active" aria-current="page" href="#">Home</a> -->
        </li>
         <li class="nav-item">
          <%= link_to 'Books',books_path,class:"nav-link" %>
       <!--   <a class="nav-link active" aria-current="page" href="#">Home</a> -->
        </li>
        
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
Hi There!


Welcome to OOty Nice to Meet You!

app/views/home/index.html.erb
<h1> Hello World!</h1>

<h2> This is my first rails webpage</h2>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>University Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">

    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

<!--
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
-->

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address,class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone,class:'form-control' %>
  </div>
  <br/>
  <div>
    <%= form.submit class:'btn btn-info' %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">

  <div class="card">
  <h5 class="card-header">Student Details</h5>
  <div class="card-body">
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= student.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </div>
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>


<div id="students">
  <div class="jumbotron" >
  <table class="table table-striped table-bordered table-hover">
      <thead class="table-light">
      <tr>
        <th>Student Name</th>
         
        <th>Student Address</th>
        
        <th>Phone</th>
        <th></th>
        <th></th>

    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td><%=student.name%></td>
        <td><%=student.address%></td>
        <td ><%=student.phone%></td>
        <td> <%= link_to "Show this student", student %> </td>
        <td><%= link_to "Edit this studet", edit_student_path(student) %> </td>
        <td><%= button_to "Delete", student, method: :delete ,class:'btn btn-danger' %></td>
      </tr>
      <%end %>
    </tbody>
</table>




<%= link_to "New student", new_student_path,class:'btn btn-success' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back", students_path, class:'btn btn-secondary' %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student),class:'btn btn-primary mt-1' %>

  <%= link_to "Back to students", students_path,class:'btn btn-secondary mt-1' %>
  <br/>
  <br/>
  <%= button_to "Destroy this student", @student, method: :delete,class:'btn btn-danger' %>
</div>